mysite/allapps/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.contrib import admin
app_name = "allapps"

urlpatterns = [
    url(r'^applicativo1/', views.App1View.as_view(), name='app1'),
    url(r'^applicativo1_result', views.App1_outputView.as_view(), name='app1_result'),
    url(r'^applicativo2/', views.App2View.as_view(), name='app2'),
    url(r'^applicativo2_result', views.App2_outputView.as_view(), name='app2_result'),
    url(r'^applicativo3/', views.App3View.as_view(), name='app3'),
    url(r'^applicativo3_tool1', views.App3tool1View.as_view(), name='app3tool1'),
    url(r'^applicativo3_tool2', views.App3tool2View.as_view(), name='app3tool2'),
    url(r'^applicativo3_tool3', views.App3tool3View.as_view(), name='app3tool3'),
    url(r'^contatti', views.contattiView.as_view(), name='contatti'),
]
admin.autodiscover()

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.http import HttpResponseRedirect

from allapps import views

urlpatterns = [
    
    url(r'^$', lambda r: HttpResponseRedirect('home/')),

    url(r'home/', views.HomeView.as_view(), name='home'),
    path('allapps/', include('allapps.urls')),
    path('admin/', admin.site.urls),
]

mysite/allapps/models.py
import datetime
from datetime import date
from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django.core.validators import MaxValueValidator, MinValueValidator, int_list_validator


# Useful links:
# https://django-book.readthedocs.io/en/latest/chapter05.html
# https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Models
# Models https://docs.djangoproject.com/en/3.0/topics/db/models/#relationships
# Models fields https://docs.djangoproject.com/en/3.0/ref/models/fields/#django.db.models.Field.verbose_name
# Validators https://docs.djangoproject.com/en/3.0/ref/validators/#minvaluevalidator
# Model instance reference https://docs.djangoproject.com/en/3.0/ref/models/instances/#validating-objects

# NB: If you make changes to a Django model, you’ll need to make the same
# changes inside your database to keep your database consistent with the model.
# We’ll discuss some strategies for handling this problem later in this chapter.
#==> https://django-book.readthedocs.io/en/latest/chapter05.html

# Django provides an easy way of committing the SQL to the database:
# the syncdb command:
# python manage.py syncdb


##### Client può essere un produttore o uno smaltitore
class Client(models.Model):
    id_Client = models.CharField("ID Cliente",max_length=50,primary_key=True)
    
    KIND_CHOICHES =  [("produttore", "Produttore"),("smaltitore", "Smaltitore"),]
    kind = models.CharField("Tipologia",max_length=20,choices = KIND_CHOICHES)
    
    lat  = models.DecimalField("latitudine", max_digits = 15, decimal_places = 10)
    long = models.DecimalField("longitudine", max_digits = 15, decimal_places = 10)
    timewindow_LB  = models.TimeField("Apertura",default=datetime.time(9 ,00))
    timewindow_UB  = models.TimeField("Chiusura",default=datetime.time(17,00))
    service_time = models.IntegerField("Tempo di servizio stimato [mm]",validators=[MinValueValidator(0)],default = 30)
    
    def __str__(self):
        return self.id_Client
    
    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clienti'


class UnitaLocale(models.Model):
    id_Client = models.ForeignKey(Client,on_delete=models.PROTECT,verbose_name="id cliente")
    progressivo_sede = models.PositiveIntegerField("Progressivo sede")

    nome_sede = models.CharField("nome sede", max_length=200, primary_key=True)
    lat = models.DecimalField("latitudine", max_digits=15, decimal_places=10)
    long = models.DecimalField("longitudine", max_digits=15, decimal_places=10)
    timewindow_LB = models.TimeField("Apertura", default=datetime.time(9, 00))
    timewindow_UB = models.TimeField("Chiusura", default=datetime.time(17, 00))
    service_time = models.IntegerField("Tempo di servizio stimato [mm]", validators=[MinValueValidator(0)], default=30)

    """
    def save(self, *args, **kwargs):
        if self.pk is None:
            try:
                highest_number = UnitaLocale.objects.filter(id_Client=self.id_Client).order_by('-progressivo_sede').all()[0].progressivo_sede
                self.progressivo_sede = highest_number + 1
            except ObjectDoesNotExist:
                self.progressivo_sede = 1

        super(UnitaLocale, self).save(*args, **kwargs)
    """

    class Meta:
        verbose_name = 'Unità locale'
        verbose_name_plural = 'Unità locali'

class Carrier(models.Model):
    id_Carrier = models.CharField("ID Trasportatore",max_length=50,primary_key=True) #Innocenti / altri
    address = models.CharField("indirizzo",max_length=50)
    
    class Meta:
        verbose_name = 'Trasportatore'
        verbose_name_plural = 'Trasportatori'
    
class Transporter(models.Model):
    plate_number = models.CharField("Targa",max_length=50,primary_key=True)

    TYPE_CHOICHES = [("motrice", "motrice"), ("rimorchio", "rimorchio"), ]
    trasporter_type = models.CharField("Tipologia mezzo",max_length=50, default = False,choices = TYPE_CHOICHES)
    carrier_name = models.ForeignKey(Carrier,on_delete=models.PROTECT,verbose_name = "Trasportatore proprietario")
    add_trailer = models.BooleanField("può agganciare un rimorchio",default = False)

    def __str__(self):
        return self.plate_number

    class Meta:
        verbose_name = 'mezzo di trasporto'
        verbose_name_plural = 'mezzi di trasporto'

class Truck(models.Model):
    head    = models.ForeignKey(Transporter,related_name='head', verbose_name="Motrice", on_delete=models.PROTECT,limit_choices_to={'trasporter_type': "motrice"},)
    trailer = models.ForeignKey(Transporter,related_name='trailer', verbose_name="Rimorchio", blank=True, null=True, on_delete=models.PROTECT,limit_choices_to={'trasporter_type': "rimorchio"},)
    load_capacity = models.PositiveIntegerField("Casse trasportabili",default = 1,validators=[MaxValueValidator(2)])
    is_available = models.BooleanField("disponibilità al servizio",default = True)

    class Meta:
        verbose_name = 'Automezzo'
        verbose_name_plural = 'Automezzi'

    def __str__(self):

        if str(self.trailer) == str(None):
            return str(self.head)
        else:
            return str(self.head) + "  " + str(self.trailer)



class Cer(models.Model):
    id_cer = models.CharField(verbose_name = "codice CER",max_length=50,primary_key=True)
    description = models.CharField("descrizione CER",max_length = 100) ## definire validator da lista di ammissibili
    
    class Meta:
        verbose_name = 'CER'
        verbose_name_plural = 'Codici CER'
    
    
class Mission(models.Model): ## programmazione

    id_exit= models.AutoField("ID uscita",primary_key=True)    
    date = models.DateField("data prevista",auto_now=False) # giorno ritiro/consegna
    Client_origin      = models.ForeignKey(Client, related_name = 'origin', on_delete=models.PROTECT,verbose_name = "Origine trasporto")
    Client_destination = models.ForeignKey(Client, related_name = 'destination', on_delete=models.PROTECT,verbose_name = "Destinazione trasporto")
    case_number = models.PositiveIntegerField("numero casse",validators=[MinValueValidator(1)],)
    # is_scheduled = ....

    class Meta:
        verbose_name = 'Missione'
        verbose_name_plural = 'Missioni'

class Fir(models.Model):
    fir_number = models.CharField("Numero FIR",max_length=50,primary_key=True)
    exit_id = models.ForeignKey(Mission, on_delete=models.PROTECT,verbose_name = "ID_uscita")
    cer = models.ForeignKey(Cer, on_delete=models.PROTECT,verbose_name = "CER")
    net_weight = models.PositiveIntegerField("peso netto")
    id_producer = models.ForeignKey(Client, related_name = 'producer', on_delete=models.PROTECT,verbose_name = "Produttore")
    id_disposer = models.ForeignKey(Client, related_name = 'disposer', on_delete=models.PROTECT,verbose_name = "Smaltitore")
    id_carrier = models.ForeignKey(Carrier, on_delete=models.PROTECT,verbose_name = "Trasportatore")
    
    def val_truck(self):
        if self.plate_number_truck.is_trailer == True:
            raise ValidationError(
                ('La targa inserita non corrisponde ad un automezzo'),
                params={'valore': self.plate_number_truck},)
            
    def val_trailer(self):
        if self.plate_number_trailer.is_trailer == False:
            raise ValidationError(
                ('La targa inserita non corrisponde ad un rimorchio'),
                params={'valore': self.plate_number_trailer},)      
            
    plate_number_truck = models.ForeignKey(Transporter, related_name = 'truck_plate',on_delete=models.PROTECT,validators = [val_truck],verbose_name = "Targa motrice")
    plate_number_trailer = models.ForeignKey(Transporter, related_name = 'trailer_plate', on_delete=models.PROTECT,validators = [val_trailer],verbose_name = "Targa rimorchio")
    
    class Meta:
        verbose_name = 'Fir'
        verbose_name_plural = 'Formulari'
    
    
class Mix_unloading(models.Model): ## programmazione delle attività di selezione
    id_Client = models.ForeignKey(Client, on_delete=models.CASCADE,verbose_name = "ID Cliente")
        
    date = models.DateField(verbose_name = "data prevista") # data in cui si prevede avvenga lo scarico
    working_shift = models.PositiveSmallIntegerField(verbose_name = "turno previsto",validators=[MinValueValidator(1),MaxValueValidator(2)]) # turno in cui si prevede avvenga lo scarico
    quantity = models.PositiveIntegerField(verbose_name = "quantità prevista")
            
    def horizon_included(self,orizzonte):
        now = timezone.now()
        if (now <= self.date) and  (self.date <= now + datetime.timedelta(days=orizzonte)):
            return True
        else:
            return False
        
    class Meta:
        verbose_name = 'Scarico 150106'
        verbose_name_plural = 'Scarico misti'
        
        
# input number according to App_1 input list in document "integrazioni informative REMIND"
class Input_App1(models.Model):
    horizon_LB = models.DateField() #1
    horizon_UB = models.DateField() #1
    dailyshifts = models.PositiveIntegerField(validators=[MinValueValidator(1)],default = 2) #2
    shift_1_hours = models.PositiveIntegerField(default = 6)  #3
    shift_2_hours = models.PositiveIntegerField(default = 3)  #3
    shift_3_hours = models.PositiveIntegerField(default = 0)  #3
    operator_wage = models.PositiveIntegerField(default = 15) #4
    max_operators = models.PositiveIntegerField(default = 8)  #5
    min_op_sort1 = models.PositiveIntegerField(default = 3)   #6
    min_op_sort2 = models.PositiveIntegerField(default = 6)   #6
    firstTO2nd_sort = models.PositiveIntegerField(validators=[MaxValueValidator(100)],default = 5) #7
    setup_sort1 = models.IntegerField(validators=[MinValueValidator(0)],default = 7)  #8
    setup_sort2 = models.IntegerField(validators=[MinValueValidator(0)],default = 15) #8

mysite/mysite/templates/front-end/app1.html
{% extends "base_generic.html" %}

{% block content %}
{% load static bootstrap4 %}

{% bootstrap_css %}
{% bootstrap_javascript %}


<form action="{% url 'allapps:app1' %}" method="post">
    {% csrf_token %}
    <fieldset class="module aligned ">

            <div class="form-row field-horizon_LB">
                    <div>
                            <label class="required" for="id_horizon_LB">Inizio programmazione:</label>
                                <input type="date" value = "2020-09-21" name="horizon_LB" class="vDateField" size="10" required="" id="id_horizon_LB"><span class="datetimeshortcuts">
                    </div>
            </div>
        
            <div class="form-row field-horizon_UB">
                    <div>
                            <label class="required" for="id_horizon_UB">Fine programmazione:</label>
                                <input type="date" value = "2020-09-26" name="horizon_UB" class="vDateField" size="10" required="" id="id_horizon_UB"><span class="datetimeshortcuts">
                    </div>
            </div>
<!--
            <div class="form-row field-dailyshifts">
                    <div>
                            <label class="required" for="id_dailyshifts">Turni giornalieri:</label>
                                <input type="number" name="dailyshifts" value="2" class="vIntegerField" min="0" required="" id="id_dailyshifts">
                    </div>
            </div>
-->
            <div class="form-row field-shift_1_hours">
                    <div>
                            <label class="required" for="id_shift_1_hours">Ore 1°turno:</label>
                                <input type="number" name="shift_1_hours" value="6" class="vIntegerField" min="0" required="" id="id_shift_1_hours">
                    </div>
            </div>
        
            <div class="form-row field-shift_2_hours">
                    <div>
                            <label class="required" for="id_shift_2_hours">Ore 2°turno:</label>
                                <input type="number" name="shift_2_hours" value="3" class="vIntegerField" min="0" required="" id="id_shift_2_hours">
                    </div>
            </div>
<!--
            <div class="form-row field-shift_3_hours">
                    <div>
                            <label class="required" for="id_shift_3_hours">Ore 3°turno:</label>
                                <input type="number" name="shift_3_hours" value="0" class="vIntegerField" min="0" required="" id="id_shift_3_hours">
                    </div>
            </div>
 -->
            <div class="form-row field-operator_wage">
                    <div>
                            <label class="required" for="id_operator_wage">Costo operatore [€/h]:</label>
                                <input type="number" name="operator_wage" value="15" class="vIntegerField" min="0" required="" id="id_operator_wage">
                    </div>
            </div>
        
            <div class="form-row field-max_operators">
                    <div>
                            <label class="required" for="id_max_operators">Operatori disponibili:</label>
                                <input type="number" name="max_operators" value="8" class="vIntegerField" min="0" required="" id="id_max_operators">
                    </div>
            </div>
        
            <div class="form-row field-min_op_sort1">
                    <div>
                            <label class="required" for="id_min_op_sort1">Operatori minimi 1a selezione:</label>
                                <input type="number" name="min_op_sort1" value="3" class="vIntegerField" min="0" required="" id="id_min_op_sort1">
                    </div>
            </div>
        
            <div class="form-row field-min_op_sort2">
                    <div>
                            <label class="required" for="id_min_op_sort2">Operatori minimi 2a selezione:</label>
                                <input type="number" name="min_op_sort2" value="6" class="vIntegerField" min="0" required="" id="id_min_op_sort2">
                    </div>
            </div>
        
            <div class="form-row field-firstTO2nd_sort">
                    <div>
                            <label class="required" for="id_firstTO2nd_sort">% materiale destinato a 2a selezione</label>
                                <input type="number" name="firstTO2nd_sort" value="5" class="vIntegerField" min="0" required="" id="id_firstTO2nd_sort">
                    </div>
            </div>
        
            <div class="form-row field-setup_sort1">
                    <div>
                            <label class="required" for="id_setup_sort1">Costo attivazione 1a sel.[€]:</label>
                                <input type="number" name="setup_sort1" value="7" class="vIntegerField" required="" id="id_setup_sort1">
                    </div>
            </div>
        
            <div class="form-row field-setup_sort2">
                    <div>
                            <label class="required" for="id_setup_sort2">Costo attivazione 2a sel.[€]:</label>
                                <input type="number" name="setup_sort2" value="15" class="vIntegerField" required="" id="id_setup_sort2">
                    </div>
            </div>
        
            <div class="form-row field-overfill_treshold">
                    <div>
                            <label class="required" for="id_overfill_treshold">Soglia critica riempimento pizzale:</label>
                                <input type="number" name="overfill_treshold" value="50" class="vIntegerField" min="0" required="" id="id_overfill_treshold">
                    </div>
            </div>
        
            <div class="form-row field-finalstock_treshold">
                    <div>
                            <label class="required" for="id_finalstock_treshold">Massimo riempimento piazzali fine programmazione [%]:</label>
                                <input type="number" name="finalstock_treshold" value="10" class="vIntegerField" min="0" required="" id="id_finalstock_treshold">
                    </div>
            </div>
        
            <div class="form-row field-sort1_capacity">

                    <div>
                            <label class="required" for="id_sort1_capacity">Capacità produttiva 1a sel. [kg/h - operatore]</label>
                                <input type="number" name="sort1_capacity" value="260" class="vIntegerField" min="0" required="" id="id_sort1_capacity">
                    </div>
            </div>
        
            <div class="form-row field-sort2_capacity">
                    <div>
                            <label class="required" for="id_sort2_capacity">Capacità produttiva 2a sel. [kg/h - operatore]</label>
                                <input type="number" name="sort2_capacity" value="220" class="vIntegerField" min="0" required="" id="id_sort2_capacity">
                    </div>
            </div>
        
            <div class="form-row field-sort1_maxstock">
                    <div>
                            <label class="required" for="id_sort1_maxstock">Capacità piazzale [kg]:</label>
                                <input type="number" name="sort1_maxstock" value="60000" class="vIntegerField" min="0" required="" id="id_sort1_maxstock">
                    </div>
                
            </div>
        
            <div class="form-row field-sort2_maxstock">
                    <div>
                            <label class="required" for="id_sort2_maxstock">Capacità buffer 2a selezione [kg]:</label>
                                <input type="number" name="sort2_maxstock" value="10000" class="vIntegerField" min="0" required="" id="id_sort2_maxstock">
                    </div>
            </div>
        
    </fieldset>
    <input style="font-weight: bold"  id="btnGenera" type="submit" value="Genera programmazione ottimale"
     name="Submit" id="frm1_submit" />

</form>

<div id="lblWait"></div>

{% if scarichi_prev %}
    <div id="completato"> Stato del problema: <font color="darkgreen"> Completato </font><br></div>
    {% if optimal %}
    <font color="darkgreen"> Per conoscere i dettagli della soluzione trovata clicca sul pulsante <i> <b> risultati applicazione </b> </i> </font>
    {%endif%}
    <br>
{%endif%}


    <script>
    $("#btnGenera").click(function() {
        $("#completato").hide();
        $("#lblWait").html('Stato del problema: <font color="darkgreen">  In esecuzione </font>');
    })
    </script>

{% if no_result %}
<font color="darkred"> non sono previsti conferimenti per il periodo selezionato </font>

    <br>
    <br>
{%endif%}

{% if infeasible %}
<font color="darkred"> Il problema non ammette solouzione ammissibile </font>

    <br>
    <br>
{%endif%}

<br>
Se vuoi visualizzare la programmazione ottima calcolata, visita la pagina dei risultati:
<form action="{% url 'allapps:app1_result' %}" method="get">
<button style="font-weight: bold;" type = "submit" id="myButton"  class="float-left submit-button" > <font color="darkblue"> Risultati applicazione </font> </button>
</form>

{% endblock %}

mysite/mysite/templates/front-end/app1_output.html
{% extends "base_generic.html" %}
{% load static %}
{% block content %}

{% load static bootstrap4 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

Seleziona il periodo di cui vuoi conoscere la programmazione ottimale delle attività di selezione
<br>
<br>

    <form action="{% url 'allapps:app1_result' %}" method="post">
        {% csrf_token %}
        <fieldset class="module aligned ">

            <div class="form-row field-horizon_LB">
                <div>
                    <label class="required" for="id_horizon_LB">&emsp;Inizio programmazione:</label>
                    <input type="date" value = "2020-09-21"  name="horizon_LB" class="vDateField" size="10" required=""
                           id="id_horizon_LB"><span class="datetimeshortcuts">
                </div>
            </div>

            <div class="form-row field-horizon_UB">
                <div>
                    <label class="required" for="id_horizon_UB">&emsp;Fine programmazione  :</label>
                    <input type="date" value = "2020-09-26" name="horizon_UB" class="vDateField" size="10" required=""
                           id="id_horizon_UB"><span class="datetimeshortcuts">
                </div>
            </div>

        </fieldset>
        <br>
        <input style="font-weight: bold;" type="submit" value="Cerca"
               name="Submit" id="frm_submit"/>

    </form>
    
    {% if App1_output_result_detail %}
        Stato di completamento :
        {% for state in App1_output_result_detail %}
            <font color="darkgreen"> {{ state.is_running }}</font><br>
        {% endfor %}
    {% endif %}
    <br>
    {% if App1_output_result %}
        Soluzione ottima:
                </br>
            <hr>
        <table  border="3" class="dataframe">
        <thead>
    <tr style="text-align: center;">
                <th>Data</th>
                <th>Turno</th>
                <th>1a selezione</th>
                <th>2a selezione</th>
                <th>operatori 1a sel.</th>
                <th>operatori 2a sel.</th>
                <th>Quantità 1a sel.</th>
                <th>Quantità 2a sel.</th>

            </tr>
    </thead>
    <tbody>
                {% for r in App1_output_result.table_data %}
                    <tr style="text-align: center;">
                        {% for data_point in r %}
                        <td> {{  data_point }} </td>
                        {% endfor  %}
                    </tr>

                {% endfor %}
</tbody>
                </table>

    {% endif %}


    {% if no_result %}
    <font color="darkred"> Per il periodo selezionato non è stata ancora richiesta la programmazione delle attività di selezione. </font>
        <br>
    Clicca qui se vuoi richiederne il calcolo:
        <br>
        <br>
     <form action="{% url 'allapps:app1' %}" method="get">

         <button style="font-weight: bold;" type = "submit" id="myButton" class="float-left submit-button" > <font color="darkblue"> Schedulatore delle attività di selezione </font> </button>
    </form>
    {% endif %}

{% endblock %}

mysite/mysite/templates/front-end/app2.html
{% extends "base_generic.html" %}

{% block content %}
{% load static bootstrap4 %}

{% bootstrap_css %}
{% bootstrap_javascript %}



Benvenuto nel modulo di programmazione delle attività di trasporto
<br>
Per un utilizzo corretto dell'applicazione assicurati di aver eseguito le seguenti operazioni:
<br>
    <br>
<ul>
<li>Aggiornare gli automezzi disponibili nella sezione admin</li>
<li>Inserire tutte le missioni previste per il giorno considerato</li>
<li>Attivare il server delle mappe openstreetmap </li>
</ul>



Seleziona ora il giorno per cui vuoi generare i percorsi ottimi delle missioni di recupero casse
<br>
<br>

<form action="{% url 'allapps:app2' %}" method="post">
    {% csrf_token %}
    <fieldset class="module aligned " >

            <div class="form-row field-date">
                    <div>
                            <label class="required" for="id_date">Data:</label>
                                <input type="date" name="date" value = "2020-08-30" class="vDateField" size="10" required="" id="id_date"><span class="datetimeshortcuts">
                    </div>
            </div>

            <div class="form-row field-time_cost">
                    <div>
                            <label class="required" for="id_time_cost">Costo orario:</label>
                                <input type="number" name="time_cost" value="15" class="vIntegerField" min="0" required="" id="id_time_cost">
                    </div>
            </div>

            <div class="form-row field-horizon_UB">
                    <div>
                            <label class="required" for="id_distance_cost">Costo al km:</label>
                                <input type="number" name="distance_cost" value="15" class="vIntegerField" min="0" required="" id="id_distance_cost">
                    </div>
            </div>
            <br>
            Seleziona il solutore da utilizzare per la soluzione del problema:
            <br>
            <br>
            <input type="radio" id="gurobi" name="solver" value="GRB" checked>
            <label for="male">Gurobi®</label><br>
            <input type="radio" id="mip" name="solver" value="CBC">
            <label for="female">Python-MIP</label><br>
            <input type="radio" id="euristica" name="solver" value="euristica">
            <label for="other">Euristica-IASI</label>
            <br>

    </fieldset>
    <br>
    <input type="submit"  id="btnGenera" value="Genera percorsi" style="font-weight: bold;"
     name="Submit" id="frm1_submit"  />

    <div id="lblWait"></div>


</form>




{% if model_running %}
    <div id="completato"> Stato del problema: <font color="darkgreen"> {{ model_running.is_running }}</font><br></div>
    <br>
    Per conoscere i dettagli delle programmazione logistica clicca qui:
    <form action="{% url 'allapps:app2_result' %}" method="get">
    <button type = "submit" id="myButton" style="font-weight: bold;" class="float-left submit-button" > <font color="darkblue"> Instradamento ottimale </font> </button>
    </form>
    <br>
{%endif%}

<br>

{% if missioni_prev %}
    Missioni previste per la data selezionata: <br>
    {% for missione in missioni_prev %}
        {% if missione.case_number == 1 %}
            Ritiro di {{missione.case_number}} cassa presso {{missione.Client_origin}} da conferire a {{missione.Client_destination}}<br>
        {%endif%}
        {% if missione.case_number != 1 %}
            Ritiro di {{missione.case_number}} casse presso {{missione.Client_origin}} da conferire a {{missione.Client_destination}}<br>
        {%endif%}
    {%endfor%}
{%endif%}

{% if no_result %}
<font color="darkred"> Non sono previste missioni per la data selezionata. </font>

    <br>
    <br>
{%endif%}

<br>
<br>
Se vuoi visualizzare le rotte ottime calcolate, visita la pagina dei risultati:
<form action="{% url 'allapps:app2_result' %}" method="get">
<button style="font-weight: bold;" type = "submit" id="myButton"  class="float-left submit-button" > <font color="darkblue"> Risultati applicazione </font> </button>
</form>



    <script>
    $("#btnGenera").click(function() {
        $("#completato").hide();
        $("#lblWait").html('Stato del problema: <font color="darkgreen">  In esecuzione </font>');
    })



    </script>

{% endblock %}

mysite/mysite/templates/front-end/app2_output.html
{% extends "base_generic.html" %}
{% load static %}
{% block content %}

{% load static bootstrap4 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

    <style>

    td {
  text-align: center;
  vertical-align: middle;
}

    </style>
Seleziona il giorno di cui vuoi conoscere i percorsi ottimi delle missioni di trasporto
<br>
<br>

    <form action="{% url 'allapps:app2_result' %}" method="post">
        {% csrf_token %}
        <fieldset class="module aligned ">

            <div class="form-row field-date">
                <div>
                    <label class="required" for="id_date">&emsp;Data:</label>
                    <input type="date" value = "2020-08-30" name="date" class="vDateField" size="10" required=""
                           id="id_date"><span class="datetimeshortcuts">
                </div>
            </div>

        </fieldset>
        <br>
        <input type="submit" value="Cerca" style="font-weight: bold;"
               name="Submit" id="frm_submit"/>

    </form>



    {% if App2_output_result_detail %}
        Stato di completamento : <font color="darkgreen"> {{ App2_output_result_detail.is_running }}</font><br>
    {% endif %}

    <br>
    {% if App2_output_result %}
        Soluzione ottima: <br>
        {% for result in App2_output_result %}
            <hr>
            Automezzo: <b> {{ result.truck}} </b>
            {% if result.truck_is_used == False %}
            <font color="darkred">  Non è necessario utilizzare questo automezzo </font><br>
            {%endif%}


            {% if result.truck_is_used == True %}
            <font color="darkblue"> Rotta ottima: </font>
                </br>
                </br>
        <table border="3" class="dataframe">
        <thead>
    <tr style="text-align: center;">
                <th>Ordine di visita</th>
                <th>Nome Destinazione</th>
                <th>Latitudine</th>
                <th>Longitudine</th>
                <th>Carico/Scarico</th>
                <th>Orario di arrivo</th>
                <th>Orario di partenza</th>
                <th>Carico alla partenza</th>

            </tr>
    </thead>
    <tbody>
                {% for r in result.table_data %}
                    <tr>
                        {% for data_point in r %}
                        <td> {{  data_point }} </td>
                        {% endfor  %}
                    </tr>

                {% endfor %}

</tbody>
                </table>
            {%endif%}
        {% endfor %}
    {% endif %}


    {% if no_result %}
    <font color="darkred"> Per il giorno selezionato non è stata ancora richiesta la programmazione delle attività di trasporto. </font><br>
    Clicca qui se vuoi richiederne il calcolo:
        <br>
        <br>
     <form action="{% url 'allapps:app2' %}" method="get">

    <button style="font-weight: bold;" type = "submit" id="myButton" class="float-left submit-button" > <font color="darkblue"> Route Planner </font> </button>
    </form>
    {% endif %}

{% endblock %}

mysite/mysite/templates/front-end/map_tool3.html
{% autoescape off %}
    {{ mymappa_html }}
{% endautoescape %}